In [210]:
import numpy as np
import pandas as pd
import seaborn as sns

In [211]:
df=pd.read_csv('fifa_world_cup_2026_player_performance.csv')

In [212]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [213]:
df.shape

(54600, 75)

In [214]:
df.duplicated().sum() #For duplicate rows

np.int64(0)

In [215]:
df.T.duplicated().sum() #For duplicate columns

np.int64(0)

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [217]:
missing=df.isnull().sum()
print(missing[missing>0])

Series([], dtype: int64)

In [218]:
df.drop(['player_id','player_name','height_cm','weight_kg','match_id','match_date'],axis=1,inplace=True)

In [219]:
cat_col=df.select_dtypes(include='object')

In [220]:
cat_col

,nationality,team,position,preferred_foot,club_name,stadium,city,opponent_team,tournament_stage,match_result
0,Spanish,Spain,Goalkeeper,Left,RB Salzburg,Hard Rock Stadium,Miami,South Africa,Group Stage,W
1,Spanish,Spain,Midfielder,Right,Chelsea,Hard Rock Stadium,Miami,South Africa,Group Stage,W
2,Spanish,Spain,Midfielder,Left,AIK,Hard Rock Stadium,Miami,South Africa,Group Stage,W
3,Spanish,Spain,Forward,Right,PSV Eindhoven,Hard Rock Stadium,Miami,South Africa,Group Stage,W
4,Spanish,Spain,Defender,Left,Juventus,Hard Rock Stadium,Miami,South Africa,Group Stage,W
...,...,...,...,...,...,...,...,...,...,...
54595,Iraqi,Iraq,Defender,Right,Pohang Steelers,Estadio BBVA,Monterrey,Senegal,Final,W
54596,Iraqi,Iraq,Midfielder,Right,Bunyodkor,Estadio BBVA,Monterrey,Senegal,Final,W
54597,Iraqi,Iraq,Midfielder,Left,Al-Duhail,Estadio BBVA,Monterrey,Senegal,Final,W
54598,Iraqi,Iraq,Goalkeeper,Right,Kawasaki Frontale,Estadio BBVA,Monterrey,Senegal,Final,W
54599,Iraqi,Iraq,Goalkeeper,Right,Ulsan HD,Estadio BBVA,Monterrey,Senegal,Final,W

In [224]:
cat_col=df.select_dtypes(include='object')

In [225]:
for col in cat_col:
    print(col,"=",cat_col[col].nunique())

team = 48
position = 4
preferred_foot = 2
club_name = 122
stadium = 16
city = 16
opponent_team = 48
tournament_stage = 7
match_result = 3

In [223]:
df.drop('nationality',axis=1,inplace=True)

In [226]:
counts=cat_col['club_name'].value_counts()

In [227]:
threshold=350
repl=counts[counts<=threshold].index

In [165]:
len(repl)

33

In [228]:
df['club_name']=df['club_name'].replace(repl,'other')

In [229]:
cat_col['club_name'].nunique()

122

In [168]:
cat_col

,nationality,team,position,preferred_foot,club_name,stadium,city,opponent_team,tournament_stage,match_result
0,Spanish,Spain,Goalkeeper,Left,RB Salzburg,Hard Rock Stadium,Miami,South Africa,Group Stage,W
1,Spanish,Spain,Midfielder,Right,Chelsea,Hard Rock Stadium,Miami,South Africa,Group Stage,W
2,Spanish,Spain,Midfielder,Left,AIK,Hard Rock Stadium,Miami,South Africa,Group Stage,W
3,Spanish,Spain,Forward,Right,PSV Eindhoven,Hard Rock Stadium,Miami,South Africa,Group Stage,W
4,Spanish,Spain,Defender,Left,Juventus,Hard Rock Stadium,Miami,South Africa,Group Stage,W
...,...,...,...,...,...,...,...,...,...,...
54595,Iraqi,Iraq,Defender,Right,Pohang Steelers,Estadio BBVA,Monterrey,Senegal,Final,W
54596,Iraqi,Iraq,Midfielder,Right,Bunyodkor,Estadio BBVA,Monterrey,Senegal,Final,W
54597,Iraqi,Iraq,Midfielder,Left,Al-Duhail,Estadio BBVA,Monterrey,Senegal,Final,W
54598,Iraqi,Iraq,Goalkeeper,Right,Kawasaki Frontale,Estadio BBVA,Monterrey,Senegal,Final,W
54599,Iraqi,Iraq,Goalkeeper,Right,Ulsan HD,Estadio BBVA,Monterrey,Senegal,Final,W

In [230]:
cat_cols_list=cat_col.columns.to_list()

In [231]:
cat_col['tournament_stage'].value_counts()

tournament_stage
Group Stage          30056
Round of 32           9256
Round of 16           6552
Quarter Finals        4368
Semi Finals           2184
Third Place Match     1092
Final                 1092
Name: count, dtype: int64

In [232]:
X=df.drop('market_value_eur',axis=1)
y=df['market_value_eur']

In [246]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [234]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

In [247]:
ohe_cols=cat_cols_list.copy()
ohe_cols.remove('tournament_stage')

In [238]:
ohe_cols

['team',
 'position',
 'preferred_foot',
 'club_name',
 'stadium',
 'city',
 'opponent_team',
 'match_result']

In [248]:
num_cols=X.select_dtypes(include=['int64','float64']).columns.tolist()

In [242]:
from sklearn.preprocessing import MinMaxScaler

In [249]:
transformer=ColumnTransformer(transformers=[
    ("num",MinMaxScaler(),num_cols),
    ('ordinal',OrdinalEncoder(categories=[['Group Stage','Round of 32','Round of 16','Quarter Finals','Semi Finals','Third Place Match','Final']]),['tournament_stage']),
    ('ohe',OneHotEncoder(handle_unknown='ignore',drop='first'),ohe_cols)],remainder='passthrough'
)

In [250]:
X_train=transformer.fit_transform(X_train)
X_test=transformer.transform(X_test)